Update update_repos.yml

diff --git a/.github/workflows/update_repos.yml b/.github/workflows/update_repos.yml
--- a/.github/workflows/update_repos.yml
+++ b/.github/workflows/update_repos.yml
@@ -29,6 +29,13 @@ jobs:
 
           cd /tmp/Project-Plus-Dolphin
           PKGVER=$(git tag --sort=version:refname | grep -v '\-rc$' | tail -n1)
+
+          if [ -z "$PKGVER" ]; then
+            echo "Failed to determine PKGVER"
+            exit 1
+          fi
+
+          echo "Using PKGVER=$PKGVER"
           git checkout --quiet "$(git rev-list -n 1 "$PKGVER")"
 
           ZIP_SHA="$(curl -L https://github.com/Project-Plus-Development-Team/Project-Plus-Dolphin/releases/download/$PKGVER/Project+.$PKGVER.Netplay.Linux.AppImage.zip | sha256sum | sed 's/  -//')"
